### DISCUSSION TITLE
Linux - thread 'main' panicked at crates/cli/src/main.rs:252:45: called `Option::unwrap()` on a `None` value

### DISCUSSION THREAD

**Discussion by BorboBorgo** [garyttierney/me3#109] [Bug Reports]
Hi folks,

Most actions in me3 0.4.0 are throwing this error for me when running on Linux:

`thread 'main' panicked at crates/cli/src/main.rs:252:45:
called Option::unwrap() on a None value'

**Comment by garyttierney** [comment]
It's failing to find the windows binaries dir. Do you have a `~/.config/me3/me3.toml` with an entry containing the path to where Windows binaries are located? The installer should create it with something like this:

```toml
windows_binaries_dir = "/home/gtierney/.local/share/me3/windows-bin"
crash_reporting = true
```
