### ISSUE TITLE
Documentation for first release

### ISSUE THREAD

**Issue by garyttierney** [garyttierney/me3#45]
Preview: https://me3.readthedocs.io/

> [!IMPORTANT]  
> Expect broken links. Not all pages are created or written.

- [x] Welcome page
   - [x] Links to guides on installation and launching
   - [x] Download links 
- [x] Blog post on release
    - [x] Cover mod profile creation for mod authors
    - [x] Show installation process
        - [ ] Cover how "overhaul" mods can distribute it separately
    - [x] Thank contributors, past authors
- [ ] Getting started guide 
    - [x] Windows installation 
    - [x] Linux installation
    - [x] Brief configuration reference
    - [x] Launching a mod on Windows
    - [x] Launching a mod on Linux
- [ ] Limitations (can't merge mods) - what category? maybe need to consider pages for different audiences (mod author vs. end-user) 
- [x] Creating and managing profiles (needs supporting development work)
    - [x]  me3 CLI should look for "installed" profiles in a standardized per-user path by default and be able to run them by filename
         - [x] `me3 -p <profile-id>` 
- [x] me3 Developer guide
    - [x] Update documentation on using xwin to cross-compile from Linux
    - [ ] Release checklist

**Comment by trey-niu** [comment]
Config file generated automatically looks like:
```toml
profileVersion = "v1"
natives = []
packages = []

[[supports]]
game = "nightrein"
```

While the doc website suggests:

```toml
profileVersion = "v1"

[[packages]]
id = "my-cool-texture-pack" # A unique name for this package
source = "mods/MyCoolTexturePack/" # Path to the folder containing asset overrides.
                                   # This path is relative to the profile file, unless
                                   # specified as absolute.

[[natives]]
path = "mods/MyAwesomeMod.dll" # Path to the mod's DLL file
```

It is a little bit confusing. Which to follow?
